### PR TITLE
Set default BACKEND_VMM value to xen & Repro

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by fepitre** [comment]
@marmarek please take a look at those `EXTRA_CLAGS` added. Is it fine? I've done the same in `app-linux-split-gpg` PR.

**Review by marmarek — CHANGES_REQUESTED** [review]

**Comment by marmarek** [comment]
I've merged it up until https://github.com/QubesOS/qubes-gui-agent-linux/pull/115/commits/53029ef242bb7fa6bfe6d47fdb986712a628beeb - only the last commit remains.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
