### PR TITLE
Respect FocusIn/Out `mode` in a hacky way

### PR DESCRIPTION
**Pull request by locriacyber**
Attempt to recreate different focus "mode" with Xlib API. Works good enough.

@DemiMarie

### CODE REVIEW

**Comment by locriacyber** [comment]
No. I haven't used this separated patch though.

This still gets confused when VM transfer focus among its windows.

**Comment by locriacyber** [comment]
This is still buggy. When window is killed with keyboard shortcut, Mouse focus is grabbed, but never returned.

**Comment by DemiMarie** [comment]
Does e0265cd988e14ae98a7bb8eb18ca74b86f9100cf fix it?

**Comment by locriacyber** [comment]
Not entirely. I don't know much about how server-client tracks mapped windows. I only know about the X part.

The current issue is only that in AppVM 1, sometimes the focused window is destroyed without notice, then the focus is transfered to another window in AppVM 2 (because it was previously focused in dom0), but AppVM 2 don't think it has focus.

I don't know how to fix this other than being the X server itself. We should probably retire the current gui-proxy-thingy for a proper solution (custom X server).

**Comment by DemiMarie** [comment]
> I don't know how to fix this other than being the X server itself, and use custom WM/X server that is meant to be nested (don't know if we need XFCE4 inside AppVM). We should probably retire the current gui-proxy-thingy for a proper solution (custom X server). That would get other benefits like supporting multiple input devices of the same kind.

@locriacyber: What about having a dummy window that is given focus whenever a window loses focus?
@marmarek: Am I correct that a custom X server is out of the question?

**Comment by locriacyber** [comment]
> What about having a dummy window that is given focus whenever a window loses focus?
Users probably expect to have focus returned to last window they used (when a window is closed).

**Comment by DemiMarie** [comment]
> > What about having a dummy window that is given focus whenever a window loses focus?
> 
> Users probably expect to have focus returned to last window they used (when a window is closed).

My thought was that this window would get a `FocusIn` event from the GUI daemon if it belonged to the same qube.  Otherwise, it is better for no window to have focus.

**Comment by marmarek** [comment]
> @locriacyber: What about having a dummy window that is given focus whenever a window loses focus?

I think gui-agent already does something like this. Look for `g->stub_win` usage.

**Comment by locriacyber** [comment]
Superseded by #169

**Pull request closed without merging**
