### PR TITLE
Make the PipeWire module a driver

### PR DESCRIPTION
**Pull request by DemiMarie**
Does not work yet

### CODE REVIEW

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by marmarek** [comment]
It doesn't build on Debian 12:
```
16:05:16,336 [executor:docker:9e23a0037e] output: qubes-pw-module.c: In function 'qubes_stream_data_needed':
16:05:16,336 [executor:docker:9e23a0037e] output: qubes-pw-module.c:189:16: error: incompatible types when assigning to type 'uint32_t' {aka 'unsigned int'} from type 'struct spa_fraction'
```
And also on Ubuntu 22.04 or CentOS Stream 8:
```
16:06:28,606 [executor:docker:590da0ab17] output: qubes-pw-module.c: In function 'unload_module':
16:06:28,606 [executor:docker:590da0ab17] output: qubes-pw-module.c:256:9: error: implicit declaration of function 'pw_impl_module_schedule_destroy'; did you mean 'pw_impl_module_destroy'? [-Werror=implicit-function-declaration]
16:06:28,606 [executor:docker:590da0ab17] output:   256 |         pw_impl_module_schedule_destroy(impl->module);
16:06:28,606 [executor:docker:590da0ab17] output:       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:06:28,607 [executor:docker:590da0ab17] output:       |         pw_impl_module_destroy
16:06:28,608 [executor:docker:590da0ab17] output: qubes-pw-module.c: In function 'remove_stream_cb':
16:06:28,608 [executor:docker:590da0ab17] output: qubes-pw-module.c:456:15: error: 'struct qubes_stream' has no member named 'timer'
16:06:28,608 [executor:docker:590da0ab17] output:   456 |     if (stream->timer != NULL)
16:06:28,608 [executor:docker:590da0ab17] output:       |               ^~
16:06:28,609 [executor:docker:590da0ab17] output: In file included from /usr/include/pipewire-0.3/pipewire/loop.h:32,
16:06:28,609 [executor:docker:590da0ab17] output:                  from /usr/include/pipewire-0.3/pipewire/data-loop.h:48,
16:06:28,609 [executor:docker:590da0ab17] output:                  from qubes-pw-module.c:77:
16:06:28,609 [executor:docker:590da0ab17] output: qubes-pw-module.c:457:53: error: 'struct impl' has no member named 'data_loop_utils'; did you mean 'loop_utils'?
16:06:28,610 [executor:docker:590da0ab17] output:   457 |         spa_loop_utils_destroy_source(stream->impl->data_loop_utils, stream->timer);
16:06:28,610 [executor:docker:590da0ab17] output:       |                                                     ^~~~~~~~~~~~~~~
16:06:28,610 [executor:docker:590da0ab17] output: /usr/include/spa-0.2/spa/support/loop.h:282:37: note: in definition of macro 'spa_loop_utils_method_v'
16:06:28,610 [executor:docker:590da0ab17] output:   282 |         struct spa_loop_utils *_o = o;                                  \
16:06:28,610 [executor:docker:590da0ab17] output:       |                                     ^
16:06:28,610 [executor:docker:590da0ab17] output: qubes-pw-module.c:457:9: note: in expansion of macro 'spa_loop_utils_destroy_source'
16:06:28,611 [executor:docker:590da0ab17] output:   457 |         spa_loop_utils_destroy_source(stream->impl->data_loop_utils, stream->timer);
16:06:28,611 [executor:docker:590da0ab17] output:       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:06:28,611 [executor:docker:590da0ab17] output: In file included from /usr/include/spa-0.2/spa/pod/builder.h:43,
16:06:28,611 [executor:docker:590da0ab17] output:                  from qubes-pw-module.c:73:
16:06:28,611 [executor:docker:590da0ab17] output: qubes-pw-module.c:457:76: error: 'struct qubes_stream' has no member named 'timer'
16:06:28,611 [executor:docker:590da0ab17] output:   457 |         spa_loop_utils_destroy_source(stream->impl->data_loop_utils, stream->timer);
16:06:28,611 [executor:docker:590da0ab17] output:       |                                                                            ^~
16:06:28,612 [executor:docker:590da0ab17] output: /usr/include/spa-0.2/spa/utils/hook.h:181:50: note: in definition of macro 'spa_callbacks_call'
16:06:28,612 [executor:docker:590da0ab17] output:   181 |                 _f->method((callbacks)->data, ## __VA_ARGS__);                  \
16:06:28,612 [executor:docker:590da0ab17] output:       |                                                  ^~~~~~~~~~~
16:06:28,612 [executor:docker:590da0ab17] output: /usr/include/spa-0.2/spa/support/loop.h:283:9: note: in expansion of macro 'spa_interface_call'
16:06:28,612 [executor:docker:590da0ab17] output:   283 |         spa_interface_call(&_o->iface,                                  \
16:06:28,612 [executor:docker:590da0ab17] output:       |         ^~~~~~~~~~~~~~~~~~
16:06:28,612 [executor:docker:590da0ab17] output: /usr/include/spa-0.2/spa/support/loop.h:317:49: note: in expansion of macro 'spa_loop_utils_method_v'
16:06:28,613 [executor:docker:590da0ab17] output:   317 | #define spa_loop_utils_destroy_source(l,...)    spa_loop_utils_method_v(l,destroy_source,0,__VA_ARGS__)
16:06:28,613 [executor:docker:590da0ab17] output:       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~
16:06:28,613 [executor:docker:590da0ab17] output: qubes-pw-module.c:457:9: note: in expansion of macro 'spa_loop_utils_destroy_source'
16:06:28,613 [executor:docker:590da0ab17] output:   457 |         spa_loop_utils_destroy_source(stream->impl->data_loop_utils, stream->timer);
16:06:28,613 [executor:docker:590da0ab17] output:       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:06:28,613 [executor:docker:590da0ab17] output: qubes-pw-module.c:458:11: error: 'struct qubes_stream' has no member named 'timer'
16:06:28,614 [executor:docker:590da0ab17] output:   458 |     stream->timer = NULL;
16:06:28,614 [executor:docker:590da0ab17] output:       |           ^~
16:06:28,625 [executor:docker:590da0ab17] output: qubes-pw-module.c: In function 'vchan_ready':
16:06:28,625 [executor:docker:590da0ab17] output: qubes-pw-module.c:774:31: error: 'STREAM_NOT_BLOCKED' undeclared (first use in this function)
16:06:28,625 [executor:docker:590da0ab17] output:   774 |             stream->blocked = STREAM_NOT_BLOCKED;
16:06:28,625 [executor:docker:590da0ab17] output:       |                               ^~~~~~~~~~~~~~~~~~
```

**Comment by DemiMarie** [comment]
I’m not surprised @marmarek.  Right now my main priority has been fixing Fedora and working around what appear to be multiple bugs in PipeWire.

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
How node rate is chosen? All the applications I'm running (Firefox with jitsi call, parecord, gnome-sound-recorder) shows on `pw-top` rate 44100, but both qubes-sink and qubes-source have rate 48000. I don't know if this is a problem, but looks rather wasteful (and clearly PW can do 44100).

Anyway, I did few more tests:
- parecord/paplay - works fine
- gnome-sound-recorder - works fine
- Firefox with a jitsi call - recording is rather glitchy
- Firefox with some random online recording website (online-voice-recorder.com) - also glitchy

By a coincidence, I tried also with stubdom-emulated audio instead of this module, and then recording was mostly fine, so pipewire + pipewire-pulse can work there.

As previously, I used another VM to play something and then via pavucontrol in dom0 made actual test VM to record "monitor of built-in audio analog stereo". This way I had an independent reproducible sound source for recording.

**Comment by DemiMarie** [comment]
> How node rate is chosen? All the applications I'm running (Firefox with jitsi call, parecord, gnome-sound-recorder) shows on `pw-top` rate 44100, but both qubes-sink and qubes-source have rate 48000. I don't know if this is a problem, but looks rather wasteful (and clearly PW can do 44100).

What do you have in `pipewire.conf.d`?  This seems like `default.clock.rate` is set to 48000, or that `default.clock.allowed-rates` is set to `[ 48000 ]`.  Try getting rid of that.

> Anyway, I did few more tests:
> 
> * parecord/paplay - works fine
> * gnome-sound-recorder - works fine

That’s expected.

> * Firefox with a jitsi call - recording is rather glitchy
> * Firefox with some random online recording website (online-voice-recorder.com) - also glitchy
> 
> By a coincidence, I tried also with stubdom-emulated audio instead of this module, and then recording was mostly fine, so pipewire + pipewire-pulse can work there.

What is the graph rate there?

> As previously, I used another VM to play something and then via pavucontrol in dom0 made actual test VM to record "monitor of built-in audio analog stereo". This way I had an independent reproducible sound source for recording.

Makes sense.

**Comment by marmarek** [comment]
> What do you have in `pipewire.conf.d`? This seems like `default.clock.rate` is set to 48000, or that `default.clock.allowed-rates` is set to `[ 48000 ]`. Try getting rid of that.

I don't see any of those (just comments about those options).
I do have `/usr/ahre/pipewire/pipewire.conf.avail/10-rates.conf` with a list of rates in `default.clock.allowed-rates`, not just one value, but I don't think it's used. In fact, I just tried enabling it (by copying to pipewire.conf.d) and it made qubes-* nodes run at 44100. It made a difference. It isn't perfect, but I think it's significantly better.

> What is the graph rate there?

48000 (both alsa nodes and Firefox)

**Comment by marmarek** [comment]
`parecord --rate=48000` is okay too, so it's unlikely resampling to blame (but still not impossible).

**Comment by marmarek** [comment]
Few more data points (data according to pw-top):
| scenario | qubes-source | parecord | Firefox | result |
|--------|--------|--------| ---- |--- |
| 10-rates.conf, start `parecord --rate=48000` first | 48000 | 48000 | 44100 | okay-ish
| 10-rates.conf, start `parecord --rate=48000` second or not at all | 44100 | 48000 | 44100 | similar to the above (sometimes better, sometimes worse)
| no 10-rates.conf, no parecord | 48000 | - | 44100 | okay-ish
| no 10-rates.conf, start `parecord --rate=48000` first | 48000 | 48000 | 44100 | okay-ish

At this point, I'm quite confused, because the "no 10-rates.conf" lines should be the same as the test I did yesterday, yet they are clearly better now. Maybe there is some other factor involved, like pipewire/pacat starting order? Or maybe I need to restart something else too (I restart just pipewire and pipewire-pulse between tests, wireplumber gets restarted as a side effect) ?

In any case, this PR is clearly an improvement. I feel like setting `default.clock.allowed-rates = [ 44100 48000 ]` should improve things further, but results here are not consistent (sometimes there is similar improvement even without this change).

What do you say for this plan:
1. add allowed-rates config to the package
2. merge this PR and ship it
3. wait for any further bug reports (if any)
4. if further improvements will be necessary, try to start with a _scripted_ reproducer first

?

**Comment by DemiMarie** [comment]
@marmarek I’m fine with that.

**Comment by DemiMarie** [comment]
Problem diagnosed with the help of <padenot@mozilla.com>: recording and capture are not synchronized with each other, and so it is quite easy to overrun or underrun Firefox’s internal buffers.  Chrome has larger buffers than Firefox, which is why it works when Firefox does not.  To fix this problem, audio playback and recording need to be synchronized with each other.  This ensures that playback and capture alternate and prevents the buffers from filling or emptying.

**Comment by marmarek** [comment]
This now fails to build on few distros (see CI).

**Comment by DemiMarie** [comment]
> > * TC_20_AudioVM_PipeWire_debian-12-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_debian-12-xfce/3) (failure)
> >   `AssertionError: too short audio, expected 10s, got 8.73947845804988...`
> >   
> >   * TC_20_AudioVM_PipeWire_fedora-38-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_fedora-38-xfce/3) (failure)
> >     `AssertionError: too short audio, expected 10s, got 8.30195011337868...`
> 
> Now the issue applies to plain pw-record too... If you click through the links above, you can access what was recorded (it should be one constant beep of 10s). It isn't very bad, but it was better already (no failures at https://openqa.qubes-os.org/tests/89740, if I read logs right, it was at [37fc750](https://github.com/QubesOS/qubes-gui-agent-linux/commit/37fc750b23f4963b9540c8be9e0295913f899df6))

I’m going to bisect this.

**Comment by DemiMarie** [comment]
> > * TC_20_AudioVM_PipeWire_debian-12-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_debian-12-xfce/3) (failure)
> >   `AssertionError: too short audio, expected 10s, got 8.73947845804988...`
> >   
> >   * TC_20_AudioVM_PipeWire_fedora-38-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_fedora-38-xfce/3) (failure)
> >     `AssertionError: too short audio, expected 10s, got 8.30195011337868...`
> 
> Now the issue applies to plain pw-record too... If you click through the links above, you can access what was recorded (it should be one constant beep of 10s). It isn't very bad, but it was better already (no failures at https://openqa.qubes-os.org/tests/89740, if I read logs right, it was at [37fc750](https://github.com/QubesOS/qubes-gui-agent-linux/commit/37fc750b23f4963b9540c8be9e0295913f899df6))

Let me guess: Fedora _39_ passed?  I can’t reproduce this on `fedora-39-xfce`.

**Comment by marmarek** [comment]
> Let me guess: Fedora _39_ passed?  I can’t reproduce this on `fedora-39-xfce`.

I can try another openQA run with fedora-39(-xfce) this time.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by marmarek** [comment]
> Let me guess: Fedora _39_ passed? I can’t reproduce this on `fedora-39-xfce`.

Try debian-12 maybe?

**Comment by DemiMarie** [comment]
> > Let me guess: Fedora _39_ passed? I can’t reproduce this on `fedora-39-xfce`.
> 
> Try debian-12 maybe?

Will do.

**Comment by DemiMarie** [comment]
> > * TC_20_AudioVM_PipeWire_debian-12-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_debian-12-xfce/3) (failure)
> >   `AssertionError: too short audio, expected 10s, got 8.73947845804988...`
> >   
> >   * TC_20_AudioVM_PipeWire_fedora-38-xfce: [test_228_audio_rec_unmuted_pipewire](https://openqa.qubes-os.org/tests/90247#step/TC_20_AudioVM_PipeWire_fedora-38-xfce/3) (failure)
> >     `AssertionError: too short audio, expected 10s, got 8.30195011337868...`
> 
> Now the issue applies to plain pw-record too... If you click through the links above, you can access what was recorded (it should be one constant beep of 10s). It isn't very bad, but it was better already (no failures at https://openqa.qubes-os.org/tests/89740, if I read logs right, it was at [37fc750](https://github.com/QubesOS/qubes-gui-agent-linux/commit/37fc750b23f4963b9540c8be9e0295913f899df6))

Update: On my test system, _stock_ fedora-38-xfce and debian-12-xfce both fail.  fedora-39-xfce with this PR works.

**Comment by marmarek** [comment]
What about debian-12 with this PR?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by DemiMarie** [comment]
> What about debian-12 with this PR?

Still fails.  fedora-38 does too.

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
Current test run still in progress, but I see already:
> AssertionError: too short audio, expected 10s, got 8.56936507936508, saved to /tmp/audio-sample-qubes.tests.integ.vm_qrexec_gui.TC_20_AudioVM_PipeWire_debian-12-xfce.test_228_audio_rec_unmuted_pipewire.raw

That's with this PR, pulseaudio in dom0 but with https://github.com/QubesOS/qubes-gui-daemon/pull/138 included (you can see list of PRs at https://openqa.qubes-os.org/tests/90645#settings)

**Comment by DemiMarie** [comment]
> Current test run still in progress, but I see already:
> 
> > AssertionError: too short audio, expected 10s, got 8.56936507936508, saved to /tmp/audio-sample-qubes.tests.integ.vm_qrexec_gui.TC_20_AudioVM_PipeWire_debian-12-xfce.test_228_audio_rec_unmuted_pipewire.raw
> 
> And the same for fedora-38-xfce. That's with this PR, pulseaudio in dom0 but with [QubesOS/qubes-gui-daemon#138](https://github.com/QubesOS/qubes-gui-daemon/pull/138) included (you can see list of PRs at https://openqa.qubes-os.org/tests/90645#settings)

I’m not surprised.  It turns out that the approach I took in this PR is probably going to not work well with PulseAudio in dom0 due to excessive jitter.

**Comment by marmarek** [comment]
Maybe it will work with the low-latency mode? Let me try

**Comment by marmarek** [comment]
> Maybe it will work with the low-latency mode? Let me try

Didn't help:
> AssertionError: too short audio, expected 10s, got 8.153537414965987, saved to /tmp/audio-sample-qubes.tests.integ.vm_qrexec_gui.TC_20_AudioVM_PipeWire_fedora-38-xfce.test_228_audio_rec_unmuted_pipewire.raw

**Comment by marmarek** [comment]
Interesting data point - I did a test run without this PR, but with the two others ([re-enable low latency more](https://github.com/QubesOS/qubes-core-admin-client/pull/272), and [blocking I/O on dom0 side](https://github.com/QubesOS/qubes-gui-daemon/pull/138)) and this time recording worked fine with pw-record/parecord (don't know about Firefox, as it isn't included in automatic test). But this time playback had issues: https://openqa.qubes-os.org/tests/90790

**Comment by DemiMarie** [comment]
Can you test just [blocking I/O on dom0 side](https://github.com/QubesOS/qubes-gui-daemon/pull/138)?  That’s needed for PipeWire in dom0.

**Comment by marmarek** [comment]
> Can you test just [blocking I/O on dom0 side](https://github.com/QubesOS/qubes-gui-daemon/pull/138)? That’s needed for PipeWire in dom0.

I can, but with PA in dom0 (I don't have automated switching dom0 to PW yet). Is that okay?

**Comment by DemiMarie** [comment]
> > Can you test just [blocking I/O on dom0 side](https://github.com/QubesOS/qubes-gui-daemon/pull/138)? That’s needed for PipeWire in dom0.
> 
> I can, but with PA in dom0 (I don't have automated switching dom0 to PW yet). Is that okay?

That would actually be better.  I know (from personal experience) that it works with PipeWire in dom0, but I need to make sure this does not regress PulseAudio in dom0.

**Comment by marmarek** [comment]
This still fails to build on Ubuntu jammy

**Comment by marmarek** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
